PATH_ = "MAIN FOLDER PATH HERE"
DRIVER_PATH_ = "BROWSER DRIVER PATH HERE"
DATA_PATH_ = "DATA FOLDER PATH HERE"
SITE_ = "SITE URL HERE"

USERNAME_ ="USERNAME HERE"
PASSWORD_ ="PASSWORD HERE"

PAGE_ = "PAGE HERE"
